### ISSUE TITLE
Multiple caches for multiple TTLs?

### ISSUE THREAD

**Issue by invokermain** [florimondmanca/asgi-caches#22]
Hi flori,

This project looks very exciting, very useful for my use case (web API which gets/posts data from a database), but I sat down today to try it out but realised it is quite forced in terms of how to implement, on the surface my options are:

1) Either application wide caching with one TTL.
2) Or define multiple caches with multiple TTLs and define per end point (clunky, and have to pass cache objects around whole project).

For my use case it would amazing to be able to specify routes for which a cache applies to when adding the middleware. Looking through the source code I cannot see why this would not be possible. I imagine the use could specify this by passing a list of routes, like: `['/api/y', '/api/x']` and anything that matches these routes is cached?

Might be possible to take one step further and specify TTLs per route, with the Middleware handling creating the various caches. But I am not familiar with the Cache package.

What are your thoughts? Happy to fork and try to implement the above.

Thanks

P.S. looking at the code I can see that the caching for GET requests is unique for each set of parameters. This is great for the API use-case, would be nice to have this on the documentation.

**Comment by florimondmanca** [comment]
Hi! This sounds interesting and I need to think through this a bit. Will get back to you soon. :)

Just to clarify — it seems there’s a 3rd option: reuse the same cache on multiple endpoints. You don’t *have* to specify a cache for each endpoint (although you can use multiple caches if you want). If that’s unclear from the documentation then maybe the wording needs some work.

**Comment by invokermain** [comment]
Thanks. With point two I meant if you wanted various TTLs, as far as I can see you need multiple caches, sorry I was not clear.

My motivation for asking for different TTLs comes from Flask-Caching package: https://pythonhosted.org/Flask-Caching/. In terms of user control they also allow you to cache per end point, or per end point plus query params (cache vs memoize).

A side question I had which would be nice to have documented: do you have a recommended way of passing cache objects to submodules (e.g. if you have various submodules defining a starlette router and some endpoints), or just around the project in general? Having some more example patterns in the documentation would be great 👍

**Comment by florimondmanca** [comment]
(I created #23 to address your comments on middleware-level cached routes definition. I changed the title here to specifically deal with the TTL question. :-))

Thanks for linking to Flask-Caching; I skimmed through the docs a bit.

I think one key aspect to understand is how `asgi-caches` only takes care of the HTTP layer, while actually talking to cache backends is deferred to the `async-caches` library.

OTOH, Flask-Caching merges both of these layers into one (and it even has generic memoization). This means it can provide a different API in which one `cache` object does *everything*

 We can't do that, and I don't think we *should*. This is part of the modular approach I also discuss in #23, but I can understand there may be some extra work needed on communicating this approach.

Having said that…

> if you wanted various TTLs, as far as I can see you need multiple caches

So, unless I'm completely missing something here, I really think you *can* get away with a single `Cache` instance, unless you need to talk to a different cache altogether (say, in-memory vs Redis).

As it turns out, you don't *have* to specify a TTL when building a `Cache` instance. I believe all examples in the docs do, which might fool readers into thinking that they have to pass a `ttl`, but really you don't have to. If you don't, then `async-caches` will never expire cache entries.

So if you want various TTLs while using the same `Cache` instance, you can omit the `ttl` parameter and specify TTLs per-endpoint using `@cache_control()`:

```python
from asgi_caches.decorators import cache_control, cached
from caches import Cache

cache = Cache("locmem://null")

@cached(cache)
@cache_control(max_age=30)
class View(HTTPEndpoint):
    pass
```

Now, I'll admit this is a rather verbose and perhaps non-intuitive way of doing things. The current API requires to work at the `Cache-Control` spec level by knowing that `max-age` and `ttl` are actually the same thing.

#3 suggested an arguably higher-level API in the form of an optional `ttl` parameter on `@cached`, i.e. `@cached(cache, ttl=...)`. Happy to discuss there whether that would actually be useful.

**Comment by florimondmanca** [comment]
@invokermain I created #24 and #25 to address two of your other questions/suggestions. :-) Feel free to take a look! Thanks a lot for your feedback, it's definitely very useful and much appreciated.

**Comment by invokermain** [comment]
I naively assumed middleware was Starlette specific and not part of the general ASGI framework. I have read up on the ASGI specification a bit more now.

I understand that your goal with this project is to make caching that works for any ASGI framework.

Seems like in the future there is space for higher-level caching APIs for individual frameworks built on top of this general ASGI Caching package you are making 👍 

I'll keep an eye on this project for now. If there is anything I can help with let me know.

Thanks!

**Comment by florimondmanca** [comment]
Sounds good! I’ll consider this issue resolved. :) If you’d like to help out (comments/code/etc) with the issues that branched out from this one, feel free! Happy to hear thoughts on all areas.

Thanks!
